version: '3.1'

services:
  db:
    image: postgres:13.3-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: changeme
    volumes:
      - ./data:/docker-entrypoint-initdb.d
